---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
   name: {{ .Values.certificate.name }}-{{ .Values.certificate.type }}
spec:
  secretName:  {{ .Values.certificate.name }}-{{ .Values.certificate.type }}
  issuerRef:
     {{ if  eq .Values.certificate.type "prod" }}
     name: letsencrypt
     {{ else if eq .Values.certificate.type "staging" }}
     name: letsencrypt-staging
     {{ end }}
     kind: ClusterIssuer
  commonName: {{ .Values.certificate.host }}
  dnsNames:
    -  {{ .Values.certificate.host }}
    
---
