  
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "todo.fullname" . }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    {{- range .Values.gateway.hosts }}
    - hosts:
       - {{ .host }}
      port:
          number: {{ .port }}
          name: {{ .name }}
          protocol: {{ .protocol }}
    {{- end }}
      tls:
          credentialName: {{ .Values.certificate.name }}-{{ .Values.certificate.type }}
          mode: SIMPLE
          privateKey: sds
          serverCertificate: sds



