---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-cert-1
  #  namespace: default
spec:
  secretName: ingress-cert-1
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: hello.ngxconnect.in
  dnsNames:
    - hello.ngxconnect.in
  
---
