---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: hello-subdomain-cert
  #  namespace: default
spec:
  secretName: hello-subdomain-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: hello.ngxconnect.in
  dnsNames:
    - hello.ngxconnect.in
  
---
