#@ load("@ytt:data", "data")

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
   name: #@ data.values.certificate.name+"-"+data.values.certificate.type
   

spec:
  secretName:  #@ data.values.certificate.name+"-"+data.values.certificate.type
  issuerRef:
    #@ if data.values.certificate.type == 'production':
    name: letsencrypt
    #@ elif data.values.certificate.type == 'staging':
    name: letsencrypt-staging
    #@ end
    kind: ClusterIssuer
  commonName: hello.ngxconnect.in
  dnsNames:
   #@ for/end host in data.values.ingress.hosts:
   - #@ host.host
    
---
